name: Kubernetes CI
on:
  push:
    branches:
      - dev                          
      - 'feature/**'                 #push feature/kubernetes-ci - CI runs - PR - dev - CI runs again
jobs:
  rr-app-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: check latest
        run: ls -l