name: hello_world
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "a demo build"
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: test step
        run: echo "aq demo test"
